### ISSUE TITLE
use custom datasets and cache_dir

### ISSUE THREAD

**Issue by UbeCc** [OpenLLMAI/OpenRLHF#259]
Hello! 
I've been highly impressed by OpenRLHF's accessibility and easy-to-use features.
But I've no idea how to use custom settings except for manually modify the source code.

I have two questions for this
- How to use my custom dataset that is not in the standard format
- How to use my specific cache_dir instead of the default one.

I found the first question to be "Implelemented Error". If needed, can I contribute to the two undeployed questions?

**Comment by wuxibin89** [comment]
Yes, we're very welcome for your contribution.

**Comment by hijkzzz** [comment]
Hi, OpenRLHF supports custom key name for the datasets, see https://github.com/OpenLLMAI/OpenRLHF/blob/b8fda3644733fda1efbfb847fdd0673a11eaf91f/openrlhf/datasets/prompts_dataset.py#L9

**Comment by UbeCc** [comment]
Got it. Thanks!

**Comment by catqaq** [comment]
"How to use my specific cache_dir instead of the default one."
For cache_dir,  we use hugging face dataset api.

For custom data, it is best to do some necessary preprocessing to align the format. In the future we may add a little documentation to explain how to align to a unified format or consider adding more flexibility to our data processing module, but it is not a high priority.

Feel free to reopen it~


> Hi, OpenRLHF supports custom key name for the private JSON datasets (--input_key), see
> 
> https://github.com/OpenLLMAI/OpenRLHF/blob/b8fda3644733fda1efbfb847fdd0673a11eaf91f/openrlhf/datasets/prompts_dataset.py#L9
